### ISSUE TITLE
Add additional uniqueInTable TCA Check

### ISSUE THREAD

**Issue by sejun89** [internetgalerie/ig_slug#18]
Hi, could you please add a check for "uniqueInTable"-TCA option in your SlugUtility.php? I think it should be a quick fix. I have the issue that the Extension will generate duplicated slugs in my tables, when I use the uniqueInTable configuration in my slug TCA config.

Thank you for your great tool :)

**Comment by faltrock-abone** [comment]
I have the same problem at the moment. `uniqueInSIte` is unworkable in my situation, because records are displayed on multiple domains.

I wrote a fix for this and applied it with `composer req cweagans/composer-patches` and this extra-section in my `composer.json`:
```
"extra": {
  "patches": {
    "internetgalerie/ig-slug": {
      "add uniqueInTable slug check": "https://github.com/faltrock-abone/ig_slug/commit/9d7713f0060faefcf37ce327604b8a935823ec23.patch"
    }
  }
}
```
(I needed to do `composer install` twice for the patch to be applied.)
